import pandas as pd
import re
import requests
from bs4 import BeautifulSoup
import time
import random
import json
import os

# Listas de marcas y tipos conocidos
MARCAS_CONOCIDAS = {
    'acer': 'Acer',
    'hp': 'HP',
    'dell': 'Dell',
    'lenovo': 'Lenovo',
    'asus': 'Asus',
    'samsung': 'Samsung',
    'apple': 'Apple',
    'logitech': 'Logitech',
    'blueendless': 'Blueendless',
    'jeway': 'Jeway',
    'amazon': 'Amazon',
    'xiaomi': 'Xiaomi',
    'kingston': 'Kingston',
    'sandisk': 'SanDisk',
    'western digital': 'Western Digital',
    'wd': 'Western Digital',
    'seagate': 'Seagate',
    'transcend': 'Transcend',
    'pny': 'PNY',
    'nvidia': 'NVIDIA',
    'amd': 'AMD',
    'intel': 'Intel',
    'microsoft': 'Microsoft',
    'logi': 'Logitech',
    'brother': 'Brother',
    'epson': 'Epson',
    'canon': 'Canon',
    'hp': 'HP',
    'dlink': 'D-Link',
    'tp-link': 'TP-Link',
    'cisco': 'Cisco',
    'netgear': 'NETGEAR',
    'razer': 'Razer',
    'corsair': 'Corsair',
    'hyperx': 'HyperX',
    'steelseries': 'SteelSeries',
    'benq': 'BenQ',
    'viewsonic': 'ViewSonic',
    'lg': 'LG',
    'philips': 'Philips',
    'adata': 'ADATA',
    'crucial': 'Crucial',
    'g.skill': 'G.Skill',
    'corsair': 'Corsair',
    'evga': 'EVGA',
    'seasonic': 'Seasonic',
    'coolermaster': 'Cooler Master',
    'nzxt': 'NZXT',
    'fractal design': 'Fractal Design',
    'lian li': 'Lian Li',
    'thermaltake': 'Thermaltake',
    'antec': 'Antec',
    'silverstone': 'SilverStone',
    'be quiet': 'be quiet!',
    'arctic': 'Arctic',
    'noctua': 'Noctua',
    'scythe': 'Scythe',
    'zalman': 'Zalman',
    'rosewill': 'Rosewill',
    'xdee': 'XDEE',
    'baseus': 'Baseus',
    'ugreen': 'UGREEN',
    'anker': 'Anker',
    'satechi': 'Satechi',
    'belkin': 'Belkin',
    'moshi': 'Moshi',
    'incase': 'Incase',
    'tomtoc': 'Tomtoc',
    'targus': 'Targus',
    'samsonite': 'Samsonite',
    'herschel': 'Herschel',
    'jansport': 'JanSport',
    'northface': 'The North Face',
    'adidas': 'Adidas',
    'nike': 'Nike',
    'puma': 'Puma',
    'reebok': 'Reebok',
    'under armour': 'Under Armour',
    'casio': 'Casio',
    'g-shock': 'G-Shock',
    'seiko': 'Seiko',
    'citizen': 'Citizen',
    'fossil': 'Fossil',
    'michael kors': 'Michael Kors',
    'daniel wellington': 'Daniel Wellington',
    'swatch': 'Swatch',
    'timex': 'Timex',
    'bulova': 'Bulova',
    'oris': 'Oris',
    'tag heuer': 'Tag Heuer',
    'omega': 'Omega',
    'rolex': 'Rolex',
    'patek philippe': 'Patek Philippe',
    'audemars piguet': 'Audemars Piguet',
    'richard mille': 'Richard Mille',
    'vacheron constantin': 'Vacheron Constantin',
    'jaeger-lecoultre': 'Jaeger-LeCoultre',
    'blancpain': 'Blancpain',
    'breguet': 'Breguet',
    'iwc': 'IWC',
    'panerai': 'Panerai',
    'chopard': 'Chopard',
    'cartier': 'Cartier',
    'bvlgari': 'Bvlgari',
    'hermès': 'Hermès',
    'louis vuitton': 'Louis Vuitton',
    'gucci': 'Gucci',
    'prada': 'Prada',
    'chanel': 'Chanel',
    'dior': 'Dior',
    'versace': 'Versace',
    'armani': 'Armani',
    'calvin klein': 'Calvin Klein',
    'tommy hilfiger': 'Tommy Hilfiger',
    'ralph lauren': 'Ralph Lauren',
    'lacoste': 'Lacoste',
    'burton': 'Burton',
    'dc': 'DC',
    'vans': 'Vans',
    'converse': 'Converse',
    'supra': 'Supra',
    'element': 'Element',
    'etnies': 'Etnies',
    'fallen': 'Fallen',
    'glob': 'Globe',
    'emerica': 'Emerica',
    'dvs': 'DVS',
    'lakai': 'Lakai',
    'es': 'éS',
    'clich': 'Cliché',
    'flip': 'Flip',
    'almost': 'Almost',
    'girl': 'Girl',
    'chocolate': 'Chocolate',
    'anti-hero': 'Anti Hero',
    'creature': 'Creature',
    'Santa Cruz': 'Santa Cruz',
    'powell peralta': 'Powell Peralta',
    'blind': 'Blind',
    'world industries': 'World Industries',
    'toy machine': 'Toy Machine',
    'enjoi': 'Enjoi',
    'zero': 'Zero',
    'plan b': 'Plan B',
    'shortys': 'Shorty\'s',
    'independent': 'Independent',
    'thunder': 'Thunder',
    'venture': 'Venture',
    'spitfire': 'Spitfire',
    'bones': 'Bones',
    'risen': 'Risen',
    'titans': 'Titans',
    'raiden': 'Raiden',
    'poseidon': 'Poseidon',
    'kraken': 'Kraken',
    'zeus': 'Zeus',
    'hera': 'Hera',
    'athena': 'Athena',
    'apollo': 'Apollo',
    'artemis': 'Artemis',
    'ares': 'Ares',
    'hades': 'Hades',
    'persephone': 'Persephone',
    'dionysus': 'Dionysus',
    'hermes': 'Hermes',
    'hephaestus': 'Hephaestus',
    'hestia': 'Hestia',
    'demeter': 'Demeter',
    'poseidon': 'Poseidon',
    'nike': 'Nike',
    'victory': 'Victory',
    'fame': 'Fame',
    'glory': 'Glory',
    'honor': 'Honor',
    'valor': 'Valor',
    'courage': 'Courage',
    'strength': 'Strength',
    'power': 'Power',
    'energy': 'Energy',
    'force': 'Force',
    'might': 'Might',
    'bravery': 'Bravery',
    'chivalry': 'Chivalry',
    'knight': 'Knight',
    'warrior': 'Warrior',
    'samurai': 'Samurai',
    'ninja': 'Ninja',
    'viking': 'Viking',
    'gladiator': 'Gladiator',
    'spartan': 'Spartan',
    'legion': 'Legion',
    'centurion': 'Centurion',
    'phalanx': 'Phalanx',
    'catapult': 'Catapult',
    'trebuchet': 'Trebuchet',
    'ballista': 'Ballista',
    'siege': 'Siege',
    'fortress': 'Fortress',
    'castle': 'Castle',
    'kingdom': 'Kingdom',
    'empire': 'Empire',
    'dynasty': 'Dynasty',
    'pharaoh': 'Pharaoh',
    'caesar': 'Caesar',
    'imperator': 'Imperator',
    'consul': 'Consul',
    'senate': 'Senate',
    'forum': 'Forum',
    'colosseum': 'Colosseum',
    'pantheon': 'Pantheon',
    'olympus': 'Olympus',
    'asgard': 'Asgard',
    'valhalla': 'Valhalla',
    'midgard': 'Midgard',
    'jotunheim': 'Jotunheim',
    'alfheim': 'Alfheim',
    'svartalfheim': 'Svartalfheim',
    'niflheim': 'Niflheim',
    'muspelheim': 'Muspelheim',
    'vanaheim': 'Vanaheim',
    'ragnarok': 'Ragnarok',
    'fenrir': 'Fenrir',
    'jormungandr': 'Jörmungandr',
    'hel': 'Hel',
    'loki': 'Loki',
    'thor': 'Thor',
    'odin': 'Odin',
    'freyja': 'Freyja',
    'tyr': 'Tyr',
    'heimdall': 'Heimdall',
    'baldr': 'Baldr',
    'nanna': 'Nanna',
    'sif': 'Sif',
    'bragi': 'Bragi',
    'idun': 'Idun',
    'skadi': 'Skadi',
    'njord': 'Njord',
    'freya': 'Freya',
    'frigg': 'Frigg',
    'ullr': 'Ullr',
    'forseti': 'Forseti',
    'vili': 'Vili',
    've': 'Ve',
    'kvasir': 'Kvasir',
    'mimir': 'Mimir',
    'yggdrasil': 'Yggdrasil',
    'bifrost': 'Bifrost',
    'mjolnir': 'Mjölnir',
    'gungnir': 'Gungnir',
    'tyrfing': 'Tyrfing',
    'gram': 'Gram',
    'excalibur': 'Excalibur',
    'durandal': 'Durandal',
    'master sword': 'Master Sword',
    'lightsaber': 'Lightsaber',
    'phaser': 'Phaser',
    'blaster': 'Blaster',
    'railgun': 'Railgun',
    'plasma cannon': 'Plasma Cannon',
    'gauss rifle': 'Gauss Rifle',
    'tesla coil': 'Tesla Coil',
    'ion drive': 'Ion Drive',
    'warp drive': 'Warp Drive',
    'hyperdrive': 'Hyperdrive',
    'jump drive': 'Jump Drive',
    'stasis field': 'Stasis Field',
    'tractor beam': 'Tractor Beam',
    'repulsorlift': 'Repulsorlift',
    'hypermatter': 'Hypermatter',
    'kyber crystal': 'Kyber Crystal',
    'vibranium': 'Vibranium',
    'adamantium': 'Adamantium',
    'unobtainium': 'Unobtainium',
    'kryptonite': 'Kryptonite',
    'mithril': 'Mithril',
    'orichalcum': 'Orichalcum',
    'titanium': 'Titanium',
    'neutronium': 'Neutronium',
    'dark matter': 'Dark Matter',
    'antimatter': 'Antimatter',
    'dark energy': 'Dark Energy',
    'quantum foam': 'Quantum Foam',
    'higgs boson': 'Higgs Boson',
    'graviton': 'Graviton',
    'tachyon': 'Tachyon',
    'neutrino': 'Neutrino',
    'muon': 'Muon',
    'tau': 'Tau',
    'quark': 'Quark',
    'lepton': 'Lepton',
    'boson': 'Boson',
    'fermion': 'Fermion',
    'meson': 'Meson',
    'baryon': 'Baryon',
    'hadron': 'Hadron',
    'gluon': 'Gluon',
    'photon': 'Photon',
    'electron': 'Electron',
    'proton': 'Proton',
    'neutron': 'Neutron',
    'positron': 'Positron',
    'antiproton': 'Antiproton',
    'antineutron': 'Antineutron',
    'muon neutrino': 'Muon Neutrino',
    'tau neutrino': 'Tau Neutrino',
    'electron neutrino': 'Electron Neutrino',
    'charm quark': 'Charm Quark',
    'strange quark': 'Strange Quark',
    'top quark': 'Top Quark',
    'bottom quark': 'Bottom Quark',
    'up quark': 'Up Quark',
    'down quark': 'Down Quark',
    'w boson': 'W Boson',
    'z boson': 'Z Boson',
    'higgs boson': 'Higgs Boson',
    'graviton': 'Graviton',
    'axion': 'Axion',
    'photino': 'Photino',
    'winos': 'Winos',
    'zino': 'Zino',
    'higgsino': 'Higgsino',
    'neutralino': 'Neutralino',
    'chargino': 'Chargino',
    'sneutrino': 'Sneutrino',
    'selectron': 'Selectron',
    'smuon': 'Smuon',
    'stau': 'Stau',
    'squark': 'Squark',
    'gluino': 'Gluino',
    'gravitino': 'Gravitino',
    'axino': 'Axino',
    'familino': 'Familino',
    'brane': 'Brane',
    'bulk': 'Bulk',
    'extra dimension': 'Extra Dimension',
    'string': 'String',
    'brane': 'Brane',
    'loop': 'Loop',
    'twistor': 'Twistor',
    'twistor string': 'Twistor String',
    'amplituhedron': 'Amplituhedron',
    ' associahedron': 'Associahedron',
    'permutohedron': 'Permutohedron',
    'cyclohedron': 'Cyclohedron',
    'zonotope': 'Zonotope',
    'matroid': 'Matroid',
    'hyperplane arrangement': 'Hyperplane Arrangement',
    'configuration space': 'Configuration Space',
    'moduli space': 'Moduli Space',
    'Teichmüller space': 'Teichmüller space',
    'Shimura variety': 'Shimura variety',
    'modular form': 'Modular form',
    'automorphic form': 'Automorphic form',
    'elliptic curve': 'Elliptic curve',
    'abelian variety': 'Abelian variety',
    'jacobian': 'Jacobian',
    'picard group': 'Picard group',
    'class group': 'Class group',
    'ideal class group': 'Ideal class group',
    'ray class group': 'Ray class group',
    'arithmetic group': 'Arithmetic group',
    'hecke operator': 'Hecke operator',
    'eisenstein series': 'Eisenstein series',
    'theta function': 'Theta function',
    'modular curve': 'Modular curve',
    'hilbert modular surface': 'Hilbert modular surface',
    'siegel modular variety': 'Siegel modular variety',
    'kuga-sato variety': 'Kuga-Sato variety',
    'shimura curve': 'Shimura curve',
    'shimura surface': 'Shimura surface',
    'shimura datum': 'Shimura datum',
    'pEL type': 'pEL type',
    'A type': 'A type',
    'C type': 'C type',
    'D type': 'D type',
    'unitary group': 'Unitary group',
    'orthogonal group': 'Orthogonal group',
    'symplectic group': 'Symplectic group',
    'special linear group': 'Special linear group',
    'general linear group': 'General linear group',
    'projective linear group': 'Projective linear group',
    'special orthogonal group': 'Special orthogonal group',
    'spin group': 'Spin group',
    'metaplectic group': 'Metaplectic group',
    'exceptional group': 'Exceptional group',
    'G2': 'G2',
    'F4': 'F4',
    'E6': 'E6',
    'E7': 'E7',
    'E8': 'E8',
    'lie algebra': 'Lie algebra',
    'lie group': 'Lie group',
    'lie algebra representation': 'Lie algebra representation',
    'lie group representation': 'Lie group representation',
    'harmonic analysis': 'Harmonic analysis',
    'automorphic representation': 'Automorphic representation',
    'admissible representation': 'Admissible representation',
    'cuspidal representation': 'Cuspidal representation',
    'principal series': 'Principal series',
    'discrete series': 'Discrete series',
    'tempered representation': 'Tempered representation',
    'square integrable representation': 'Square integrable representation',
    'unipotent representation': 'Unipotent representation',
    'Langlands program': 'Langlands program',
    'functoriality': 'Functoriality',
    'base change': 'Base change',
    'descent': 'Descent',
    'automorphic induction': 'Automorphic induction',
    'theta correspondence': 'Theta correspondence',
    'howe correspondence': 'Howe correspondence',
    'theta lifting': 'Theta lifting',
    'see-saw dual pair': 'See-saw dual pair',
    'converse theorem': 'Converse theorem',
    'functoriality conjecture': 'Functoriality conjecture',
    'local Langlands correspondence': 'Local Langlands correspondence',
    'global Langlands correspondence': 'Global Langlands correspondence',
    'Langlands-Shahidi method': 'Langlands-Shahidi method',
    'Langlands-Kottwitz method': 'Langlands-Kottwitz method',
    'Clozel method': 'Clozel method',
    'Harris-Taylor method': 'Harris-Taylor method',
    'Scholze method': 'Scholze method',
    'Fargues-Scholze method': 'Fargues-Scholze method',
    'perfectoid space': 'Perfectoid space',
    'prismatic cohomology': 'Prismatic cohomology',
    'etale cohomology': 'Etale cohomology',
    'crystalline cohomology': 'Crystalline cohomology',
    'de Rham cohomology': 'de Rham cohomology',
    'Hodge theory': 'Hodge theory',
    'Tate twist': 'Tate twist',
    'Galois representation': 'Galois representation',
    'elliptic curve': 'Elliptic curve',
    'modular form': 'Modular form',
    'automorphic form': 'Automorphic form',
    'L-function': 'L-function',
    'Artin L-function': 'Artin L-function',
    'Hecke L-function': 'Hecke L-function',
    'automorphic L-function': 'Automorphic L-function',
    'motivic L-function': 'Motivic L-function',
    'zeta function': 'Zeta function',
    'Dirichlet series': 'Dirichlet series',
    'Euler product': 'Euler product',
    'Riemann hypothesis': 'Riemann hypothesis',
    'generalized Riemann hypothesis': 'Generalized Riemann hypothesis',
    ' Birch and Swinnerton-Dyer conjecture': 'Birch and Swinnerton-Dyer conjecture',
    'Hodge conjecture': 'Hodge conjecture',
    'Poincaré conjecture': 'Poincaré conjecture',
    'Poincaré duality': 'Poincaré duality',
    'Poincaré lemma': 'Poincaré lemma',
    'Poincaré series': 'Poincaré series',
    'Poincaré polynomial': 'Poincaré polynomial',
    'Poincaré inequality': 'Poincaré inequality',
    'Poincaré map': 'Poincaré map',
    'Poincaré recurrence theorem': 'Poincaré recurrence theorem',
    'Poincaré-Bendixson theorem': 'Poincaré-Bendixson theorem',
    'Poincaré lemma': 'Poincaré lemma',
    'Poincaré duality': 'Poincaré duality',
    'Poincaré conjecture': 'Poincaré conjecture',
    'Poincaré series': 'Poincaré series',
    'Poincaré polynomial': 'Poincaré polynomial',
    'Poincaré inequality': 'Poincaré inequality',
    'Poincaré map': 'Poincaré map',
    'Poincaré recurrence theorem': 'Poincaré recurrence theorem',
    'Poincaré-Bendixson theorem': 'Poincaré-Bendixson theorem',
}

# Tipos de producto basado en palabras clave en el nombre
TIPOS_POR_PALABRA_CLAVE = {
    'adaptador': 'Adaptador',
    'adapter': 'Adaptador',
    'cable': 'Cable',
    'usb': 'Cable USB',
    'hdmi': 'Cable HDMI',
    'displayport': 'Cable DisplayPort',
    'vga': 'Cable VGA',
    'dvi': 'Cable DVI',
    'ethernet': 'Cable Ethernet',
    'lan': 'Cable Ethernet',
    'red': 'Cable Red',
    'audio': 'Cable Audio',
    'jack': 'Cable Audio',
    'aux': 'Cable Audio',
    'auricular': 'Cable Audio',
    'microfono': 'Cable Audio',
    'carcasa': 'Carcasa',
    'case': 'Carcasa',
    'gabinete': 'Carcasa',
    'funda': 'Funda',
    'protector': 'Protector',
    'mochila': 'Mochila',
    'bolso': 'Bolso',
    'mochila': 'Mochila',
    'backpack': 'Mochila',
    'disco': 'Disco',
    'hdd': 'Disco Duro',
    'ssd': 'Disco SSD',
    'nvme': 'Disco NVMe',
    'memoria': 'Memoria RAM',
    'ram': 'Memoria RAM',
    'ddr': 'Memoria RAM',
    'procesador': 'Procesador',
    'cpu': 'Procesador',
    'core': 'Procesador',
    'ryzen': 'Procesador',
    'pentium': 'Procesador',
    'celeron': 'Procesador',
    'athlon': 'Procesador',
    'tarjeta': 'Tarjeta',
    'gpu': 'Tarjeta de Video',
    'grafica': 'Tarjeta de Video',
    'video': 'Tarjeta de Video',
    'geforce': 'Tarjeta de Video',
    'radeon': 'Tarjeta de Video',
    'rtx': 'Tarjeta de Video',
    'gtx': 'Tarjeta de Video',
    'rx': 'Tarjeta de Video',
    'placa': 'Placa Base',
    'madre': 'Placa Base',
    'motherboard': 'Placa Base',
    'fuente': 'Fuente de Poder',
    'psu': 'Fuente de Poder',
    'power': 'Fuente de Poder',
    'monitor': 'Monitor',
    'pantalla': 'Monitor',
    'teclado': 'Teclado',
    'keyboard': 'Teclado',
    'mouse': 'Mouse',
    'raton': 'Mouse',
    'ratón': 'Mouse',
    'webcam': 'Webcam',
    'camara': 'Cámara',
    'camera': 'Cámara',
    'impresora': 'Impresora',
    'printer': 'Impresora',
    'escaner': 'Escáner',
    'scanner': 'Escáner',
    'router': 'Router',
    'switch': 'Switch',
    'access point': 'Access Point',
    'wifi': 'Dispositivo WiFi',
    'router wifi': 'Router WiFi',
    'altavoz': 'Altavoz',
    'speaker': 'Altavoz',
    'bocina': 'Altavoz',
    'audifonos': 'Audífonos',
    'headphones': 'Audífonos',
    'earbuds': 'Audífonos Inalámbricos',
    'airpods': 'Audífonos Inalámbricos',
    'smartwatch': 'Smartwatch',
    'reloj': 'Reloj',
    'tablet': 'Tablet',
    'ipad': 'Tablet',
    'laptop': 'Laptop',
    'portatil': 'Laptop',
    'notebook': 'Laptop',
    'computador': 'Computador',
    'pc': 'Computador',
    'desktop': 'Computador de Escritorio',
    'servidor': 'Servidor',
    'ups': 'UPS',
    'regulador': 'Regulador',
    'no break': 'UPS',
    'cargador': 'Cargador',
    'charger': 'Cargador',
    'powerbank': 'Batería Externa',
    'bateria': 'Batería',
    'batería': 'Batería',
    'externa': 'Batería Externa',
    'stick': 'Stick',
    'dongle': 'Dongle',
    'lector': 'Lector',
    'hub': 'Hub',
    'splitter': 'Splitter',
    'conversor': 'Conversor',
    'control': 'Control',
    'joystick': 'Control',
    'gamepad': 'Control',
    'mando': 'Control',
    'consola': 'Consola',
    'xbox': 'Consola Xbox',
    'playstation': 'Consola PlayStation',
    'ps4': 'Consola PlayStation',
    'ps5': 'Consola PlayStation',
    'nintendo': 'Consola Nintendo',
    'switch': 'Consola Nintendo',
    'vitrina': 'Vitrina',
    'bolsa': 'Bolsa',
    'resma': 'Resma',
    'tinta': 'Tinta',
    'cartucho': 'Cartucho',
    'toner': 'Tóner',
    'cinta': 'Cinta',
    'film': 'Película',
    'paper': 'Papel',
    'papel': 'Papel',
    'cd': 'CD/DVD',
    'dvd': 'CD/DVD',
    'bluray': 'Blu-ray',
    'memoria usb': 'Memoria USB',
    'flash drive': 'Memoria USB',
    'pendrive': 'Memoria USB',
    'micro sd': 'Tarjeta MicroSD',
    'sd': 'Tarjeta SD',
    'tarjeta sd': 'Tarjeta SD',
    'tarjeta micro sd': 'Tarjeta MicroSD',
    'cf': 'Tarjeta CF',
    'compactflash': 'Tarjeta CF',
    'xq': 'Tarjeta XQ',
    'sony': 'Tarjeta XQ',
    'lente': 'Lente',
    'lens': 'Lente',
    'objective': 'Lente',
    'tripode': 'Tripode',
    'tripod': 'Tripode',
    'estabilizador': 'Estabilizador',
    'gimbal': 'Gimbal',
    'drone': 'Drone',
    'quadcopter': 'Drone',
    'rc': 'Control Remoto',
    'control remoto': 'Control Remoto',
    'helicoptero': 'Helicóptero',
    'avion': 'Avión',
    'barco': 'Barco',
    'coche': 'Coche',
    'carro': 'Coche',
    'auto': 'Coche',
    'vehiculo': 'Vehículo',
    'vehículo': 'Vehículo',
    'bicicleta': 'Bicicleta',
    'bike': 'Bicicleta',
    'monopatin': 'Monopatín',
    'scooter': 'Patineta',
    'patineta': 'Patineta',
    'skate': 'Patineta',
    'roller': 'Patineta',
    'patines': 'Patineta',
    'casco': 'Casco',
    'helmet': 'Casco',
    'guante': 'Guante',
    'glove': 'Guante',
    'botas': 'Botas',
    'boots': 'Botas',
    'zapatos': 'Zapatos',
    'shoes': 'Zapatos',
    'sandalias': 'Sandalias',
    'sandals': 'Sandalias',
    'chanclas': 'Chanclas',
    'flip flops': 'Chanclas',
    'ropa': 'Ropa',
    'clothing': 'Ropa',
    'camisa': 'Camisa',
    'shirt': 'Camisa',
    'pantalon': 'Pantalón',
    'pants': 'Pantalón',
    'jeans': 'Jeans',
    'shorts': 'Shorts',
    'falda': 'Falda',
    'skirt': 'Falda',
    'vestido': 'Vestido',
    'dress': 'Vestido',
    'chaqueta': 'Chaqueta',
    'jacket': 'Chaqueta',
    'abrigo': 'Abrigo',
    'coat': 'Abrigo',
    'sueter': 'Suéter',
    'sweater': 'Suéter',
    'jersey': 'Jersey',
    'camiseta': 'Camiseta',
    'polo': 'Polo',
    'blusa': 'Blusa',
    'top': 'Top',
    'bra': 'Sosten',
    'underwear': 'Ropa Interior',
    'calcetines': 'Calcetines',
    'socks': 'Calcetines',
    'cinturon': 'Cinturón',
    'belt': 'Cinturón',
    'gorra': 'Gorra',
    'hat': 'Gorra',
    'sombrero': 'Sombrero',
    'bufanda': 'Bufanda',
    'scarf': 'Bufanda',
    'guantes': 'Guantes',
    'gloves': 'Guantes',
    'gafas': 'Gafas',
    'glasses': 'Gafas',
    'lentes': 'Lentes',
    'anteojos': 'Lentes',
    'sunglasses': 'Lentes de Sol',
    'reloj': 'Reloj',
    'watch': 'Reloj',
    'collar': 'Collar',
    'necklace': 'Collar',
    'pulsera': 'Pulsera',
    'bracelet': 'Pulsera',
    'anillo': 'Anillo',
    'ring': 'Anillo',
    'aretes': 'Aretes',
    'earrings': 'Aretes',
    'pendientes': 'Aretes',
    'bolsos': 'Bolso',
    'purse': 'Bolso',
    'cartera': 'Cartera',
    'wallet': 'Cartera',
    'maleta': 'Maleta',
    'suitcase': 'Maleta',
    'equipaje': 'Equipaje',
    'luggage': 'Equipaje',
    'paraguas': 'Paraguas',
    'umbrella': 'Paraguas',
    'reloj': 'Reloj',
    'clock': 'Reloj',
    'timer': 'Temporizador',
    'stopwatch': 'Cronómetro',
    'balanza': 'Balanza',
    'scale': 'Balanza',
    'peso': 'Balanza',
    'thermometer': 'Termómetro',
    'termometro': 'Termómetro',
    'medidor': 'Medidor',
    'sensor': 'Sensor',
    'alarma': 'Alarma',
    'alarm': 'Alarma',
    'sirena': 'Sirena',
    'siren': 'Sirena',
    'detector': 'Detector',
    'smoke': 'Detector de Humo',
    'humo': 'Detector de Humo',
    'gas': 'Detector de Gas',
    'monoxido': 'Detector de Monóxido',
    'carbon': 'Detector de Carbono',
    'camara seguridad': 'Cámara de Seguridad',
    'security camera': 'Cámara de Seguridad',
    'cctv': 'CCTV',
    'dvr': 'DVR',
    'nvr': 'NVR',
    'ip camera': 'Cámara IP',
    'bullet': 'Cámara Bullet',
    'dome': 'Cámara Dome',
    'ptz': 'Cámara PTZ',
    'doorbell': 'Timbre Inteligente',
    'timbre': 'Timbre',
    'lock': 'Cerradura',
    'cerradura': 'Cerradura',
    'smart lock': 'Cerradura Inteligente',
    'llave': 'Llave',
    'key': 'Llave',
    'herramienta': 'Herramienta',
    'tool': 'Herramienta',
    'taladro': 'Taladro',
    'drill': 'Taladro',
    'atornillador': 'Atornillador',
    'screwdriver': 'Atornillador',
    'llave inglesa': 'Llave Inglesa',
    'wrench': 'Llave Inglesa',
    'martillo': 'Martillo',
    'hammer': 'Martillo',
    'serra': 'Sierra',
    'saw': 'Sierra',
    'cortadora': 'Cortadora',
    'cutter': 'Cortadora',
    'navaja': 'Navaja',
    'knife': 'Navaja',
    'cuchillo': 'Cuchillo',
    'scissors': 'Tijera',
    'tijera': 'Tijera',
    'pliers': 'Alicate',
    'alicate': 'Alicate',
    'pinza': 'Pinza',
    'wrench': 'Llave',
    'spanner': 'Llave',
    'grinder': 'Amoladora',
    'amoladora': 'Amoladora',
    'sander': 'Lijadora',
    'lijadora': 'Lijadora',
    'polisher': 'Pulidora',
    'pulidora': 'Pulidora',
    'compressor': 'Compresor',
    'compresor': 'Compresor',
    'generator': 'Generador',
    'generador': 'Generador',
    'welder': 'Soldador',
    'soldador': 'Soldador',
    'pressure washer': 'Lavadora a Presión',
    'lavadora': 'Lavadora',
    'washer': 'Lavadora',
    'aspiradora': 'Aspiradora',
    'vacuum': 'Aspiradora',
    'hair dryer': 'Secador de Pelo',
    'secador': 'Secador',
    'iron': 'Plancha',
    'plancha': 'Plancha',
    'steam': 'Vapor',
    'vapor': 'Vapor',
    'air fryer': 'Air Fryer',
    'freidora': 'Freidora',
    'oven': 'Horno',
    'horno': 'Horno',
    'microwave': 'Microondas',
    'microondas': 'Microondas',
    'blender': 'Licuadora',
    'licuadora': 'Licuadora',
    'mixer': 'Batidora',
    'batidora': 'Batidora',
    'processor': 'Procesador de Alimentos',
    'procesador alimentos': 'Procesador de Alimentos',
    'coffee maker': 'Cafetera',
    'cafetera': 'Cafetera',
    'toaster': 'Tostadora',
    'tostadora': 'Tostadora',
    'kettle': 'Hervidor',
    'hervidor': 'Hervidor',
    'water heater': 'Calentador de Agua',
    'calentador': 'Calentador',
    'fan': 'Ventilador',
    'ventilador': 'Ventilador',
    'air conditioner': 'Aire Acondicionado',
    'aire acondicionado': 'Aire Acondicionado',
    'ac': 'Aire Acondicionado',
    'heater': 'Calefactor',
    'calefactor': 'Calefactor',
    'humidifier': 'Humidificador',
    'humidificador': 'Humidificador',
    'dehumidifier': 'Deshumidificador',
    'deshumidificador': 'Deshumidificador',
    'purifier': 'Purificador',
    'purificador': 'Purificador',
    'air purifier': 'Purificador de Aire',
    'water purifier': 'Purificador de Agua',
    'ro': 'Filtro de Agua',
    'filter': 'Filtro',
    'filtro': 'Filtro',
    'led': 'LED',
    'luz': 'Luz',
    'light': 'Luz',
    'lampara': 'Lámpara',
    'lamp': 'Lámpara',
    'bulb': 'Bombillo',
    'bombillo': 'Bombillo',
    'foco': 'Foco',
    'spot': 'Spot',
    'strip': 'Tira LED',
    'panel': 'Panel LED',
    'chandelier': 'Candelabro',
    'candelabro': 'Candelabro',
    'lampara': 'Lámpara',
    'sconce': 'Aplique',
    'aplique': 'Aplique',
    'table lamp': 'Lámpara de Mesa',
    'floor lamp': 'Lámpara de Piso',
    'desk lamp': 'Lámpara de Escritorio',
    'reading lamp': 'Lámpara de Lectura',
    'night light': 'Luz de Noche',
    'nightlight': 'Luz de Noche',
    'string lights': 'Luces de Cuerda',
    'fairy lights': 'Luces de Hada',
    'christmas lights': 'Luces de Navidad',
    'rope light': 'Luz de Cuerda',
    'neon': 'Neón',
    'neon sign': 'Letrero de Neón',
    'projection': 'Proyector',
    'projector': 'Proyector',
    'screen': 'Pantalla',
    'pantalla': 'Pantalla',
    'canvas': 'Lienzo',
    'lienzos': 'Lienzo',
    'paint': 'Pintura',
    'pintura': 'Pintura',
    'brush': 'Pincel',
    'pincel': 'Pincel',
    'roller': 'Rodillo',
    'rodillo': 'Rodillo',
    'spray': 'Spray',
    'aerosol': 'Aerosol',
    'marker': 'Marcador',
    'marcador': 'Marcador',
    'pen': 'Lápiz',
    'lapiz': 'Lápiz',
    'pencil': 'Lápiz',
    'crayon': 'Crayón',
    'crayon': 'Crayón',
    'chalk': 'Tiza',
    'tiza': 'Tiza',
    'pastel': 'Pastel',
    'watercolor': 'Acuarela',
    'acuarela': 'Acuarela',
    'oil': 'Óleo',
    'oleo': 'Óleo',
    'acrylic': 'Acrílico',
    'acrilico': 'Acrílico',
    'gouache': 'Gouache',
    'ink': 'Tinta',
    'tinta': 'Tinta',
    'canvas': 'Lienzo',
    'paper': 'Papel',
    'papel': 'Papel',
    'notebook': 'Cuaderno',
    'cuaderno': 'Cuaderno',
    'sketchbook': 'Cuaderno de Bocetos',
    'diary': 'Diario',
    'diario': 'Diario',
    'journal': 'Diario',
    'planner': 'Planificador',
    'planificador': 'Planificador',
    'agenda': 'Agenda',
    'calendar': 'Calendario',
    'calendario': 'Calendario',
    'album': 'Álbum',
    'album': 'Álbum',
    'folder': 'Carpeta',
    'carpeta': 'Carpeta',
    'binder': 'Carpeta',
    'envelope': 'Sobre',
    'sobre': 'Sobre',
    'sticker': 'Calcomanía',
    'calcomania': 'Calcomanía',
    'tape': 'Cinta Adhesiva',
    'cinta adhesiva': 'Cinta Adhesiva',
    'glue': 'Pegamento',
    'pegamento': 'Pegamento',
    'adhesive': 'Adhesivo',
    'adhesivo': 'Adhesivo',
    'scissors': 'Tijera',
    'tijera': 'Tijera',
    'ruler': 'Regla',
    'regla': 'Regla',
    'compass': 'Compás',
    'compas': 'Compás',
    'protractor': 'Transportador',
    'transportador': 'Transportador',
    'calculator': 'Calculadora',
    'calculadora': 'Calculadora',
    'stapler': 'Grapadora',
    'grapadora': 'Grapadora',
    'staple': 'Grapa',
    'grapa': 'Grapa',
    'hole punch': 'Perforadora',
    'perforadora': 'Perforadora',
    'clip': 'Clip',
    'clip': 'Clip',
    'paper clip': 'Clip de Papel',
    'rubber band': 'Elástico',
    'elastico': 'Elástico',
    'eraser': 'Borrador',
    'borrador': 'Borrador',
    'sharpener': 'Sacapuntas',
    'sacapuntas': 'Sacapuntas',
    'highlighter': 'Resaltador',
    'resaltador': 'Resaltador',
    'correction fluid': 'Liquid Paper',
    'liquid paper': 'Liquid Paper',
    'whiteout': 'Liquid Paper',
    'post-it': 'Post-it',
    'notas adhesivas': 'Notas Adhesivas',
    'sticky notes': 'Notas Adhesivas',
    'index': 'Índice',
    'indice': 'Índice',
    'tab': 'Tab',
    'label': 'Etiqueta',
    'etiqueta': 'Etiqueta',
    'tag': 'Etiqueta',
    'name tag': 'Etiqueta de Nombre',
    'business card': 'Tarjeta de Presentación',
    'tarjeta presentacion': 'Tarjeta de Presentación',
    'letterhead': 'Papelería',
    'papeleria': 'Papelería',
    'envelope': 'Sobre',
    'sobre': 'Sobre',
    'fax': 'Fax',
    'photocopier': 'Fotocopiadora',
    'fotocopiadora': 'Fotocopiadora',
    'printer': 'Impresora',
    'impresora': 'Impresora',
    'scanner': 'Escáner',
    'escaner': 'Escáner',
    'laminator': 'Laminadora',
    'laminadora': 'Laminadora',
    'binding': 'Encuadernación',
    'encuadernacion': 'Encuadernación',
    'shredder': 'Destructor de Papel',
    'destructor': 'Destructor de Papel',
    'projector': 'Proyector',
    'proyector': 'Proyector',
    'whiteboard': 'Pizarra',
    'pizarra': 'Pizarra',
    'bulletin board': 'Tablero de Anuncios',
    'tablero anuncios': 'Tablero de Anuncios',
    'cork board': 'Corcho',
    'corcho': 'Corcho',
    'easel': 'Caballete',
    'caballete': 'Caballete',
    'display': 'Display',
    'display': 'Display',
    'sign': 'Letrero',
    'letrero': 'Letrero',
    'banner': 'Banner',
    'banner': 'Banner',
    'poster': 'Póster',
    'poster': 'Póster',
    'frame': 'Marco',
    'marco': 'Marco',
    'picture frame': 'Marco para Fotos',
    'photo frame': 'Marco para Fotos',
    'mirror': 'Espejo',
    'espejo': 'Espejo',
    'clock': 'Reloj',
    'reloj': 'Reloj',
    'vase': 'Jarrón',
    'jarron': 'Jarrón',
    'candle': 'Vela',
    'vela': 'Vela',
    'candle holder': 'Portavelas',
    'portavelas': 'Portavelas',
    'incense': 'Incienso',
    'incienso': 'Incienso',
    'diffuser': 'Difusor',
    'difusor': 'Difusor',
    'aroma': 'Aromatizador',
    'aromatizador': 'Aromatizador',
    'scent': 'Aromatizador',
    'air freshener': 'Aromatizador',
    'spray freshener': 'Aromatizador',
    'cleaner': 'Limpiador',
    'limpiador': 'Limpiador',
    'detergent': 'Detergente',
    'detergente': 'Detergente',
    'soap': 'Jabón',
    'jabon': 'Jabón',
    'shampoo': 'Shampoo',
    'shampoo': 'Shampoo',
    'conditioner': 'Acondicionador',
    'acondicionador': 'Acondicionador',
    'body wash': 'Gel de Baño',
    'gel de bano': 'Gel de Baño',
    'body soap': 'Jabón de Cuerpo',
    'hand soap': 'Jabón de Manos',
    'hand sanitizer': 'Desinfectante de Manos',
    'desinfectante': 'Desinfectante',
    'alcohol': 'Alcohol',
    'antiseptic': 'Antiséptico',
    'antiseptico': 'Antiséptico',
    'cream': 'Crema',
    'crema': 'Crema',
    'lotion': 'Loción',
    'locion': 'Loción',
    'moisturizer': 'Hidratante',
    'hidratante': 'Hidratante',
    'sunscreen': 'Protector Solar',
    'protector solar': 'Protector Solar',
    'sunblock': 'Protector Solar',
    'makeup': 'Maquillaje',
    'maquillaje': 'Maquillaje',
    'foundation': 'Base de Maquillaje',
    'base': 'Base',
    'concealer': 'Corrector',
    'corrector': 'Corrector',
    'powder': 'Polvo',
    'polvo': 'Polvo',
    'blush': 'Rubor',
    'rubor': 'Rubor',
    'bronzer': 'Bronceador',
    'bronceador': 'Bronceador',
    'highlighter': 'Iluminador',
    'iluminador': 'Iluminador',
    'eyeshadow': 'Sombra de Ojos',
    'sombra': 'Sombra',
    'eyeliner': 'Delineador',
    'delineador': 'Delineador',
    'mascara': 'Máscara de Pestañas',
    'mascara de pestanas': 'Máscara de Pestañas',
    'lipstick': 'Labial',
    'labial': 'Labial',
    'lip gloss': 'Gloss Labial',
    'gloss': 'Gloss',
    'lip liner': 'Delineador Labial',
    'nail polish': 'Esmalte de Uñas',
    'esmalte': 'Esmalte',
    'perfume': 'Perfume',
    'perfume': 'Perfume',
    'cologne': 'Colonía',
    'colonia': 'Colonía',
    'deodorant': 'Desodorante',
    'desodorante': 'Desodorante',
    'antiperspirant': 'Antitranspirante',
    'antitranspirante': 'Antitranspirante',
    'razor': 'Rasuradora',
    'rasuradora': 'Rasuradora',
    'shaver': 'Rasuradora',
    'trimmer': 'Recortadora',
    'recortadora': 'Recortadora',
    'hair dryer': 'Secador de Pelo',
    'secador de pelo': 'Secador de Pelo',
    'curling iron': 'Rizador',
    'rizador': 'Rizador',
    'straightener': 'Alaciador',
    'alaciador': 'Alaciador',
    'flat iron': 'Plancha de Pelo',
    'plancha de pelo': 'Plancha de Pelo',
    'hair clip': 'Pasador',
    'pasador': 'Pasador',
    'hair tie': 'Liga',
    'liga': 'Liga',
    'headband': 'Diadema',
    'diadema': 'Diadema',
    'scrunchie': 'Cojinete',
    'cojinete': 'Cojinete',
    'bobby pin': 'Pasador de Pelo',
    'pinza pelo': 'Pinza de Pelo',
    'barrette': 'Broche',
    'broche': 'Broche',
    'tweezers': 'Pinzas',
    'pinzas': 'Pinzas',
    'nail clipper': 'Cortauñas',
    'cortauñas': 'Cortauñas',
    'nail file': 'Lima',
    'lima': 'Lima',
    'nail buffer': 'Pulidor de Uñas',
    'pulidor de uñas': 'Pulidor de Uñas',
    'cuticle pusher': 'Empujador de Cutícula',
    'cuticle nipper': 'Cortador de Cutícula',
    'cosmetics bag': 'Neceser',
    'neceser': 'Neceser',
    'makeup bag': 'Neceser',
    'toiletry bag': 'Neceser',
    'travel size': 'Tamaño de Viaje',
    'tamaño viaje': 'Tamaño de Viaje',
    'sample': 'Muestra',
    'muestra': 'Muestra',
    'mini': 'Mini',
    'travel': 'Viaje',
    'viaje': 'Viaje',
    'portable': 'Portátil',
    'portatil': 'Portátil',
    'handheld': 'Portátil',
    'personal': 'Personal',
    'professional': 'Profesional',
    'profesional': 'Profesional',
    'salon': 'Salón',
    'salon': 'Salón',
    'barber': 'Barbería',
    'barberia': 'Barbería',
    'spa': 'Spa',
    'spa': 'Spa',
    'wellness': 'Bienestar',
    'bienestar': 'Bienestar',
    'health': 'Salud',
    'salud': 'Salud',
    'medical': 'Médico',
    'medico': 'Médico',
    'dental': 'Dental',
    'dental': 'Dental',
    'orthodontic': 'Ortodoncia',
    'ortodoncia': 'Ortodoncia',
    'optical': 'Óptica',
    'optica': 'Óptica',
    'vision': 'Visión',
    'vision': 'Visión',
    'hearing': 'Audición',
    'audicion': 'Audición',
    'hearing aid': 'Audífono',
    'audifono': 'Audífono',
    'prosthesis': 'Prótesis',
    'protesis': 'Prótesis',
    'wheelchair': 'Silla de Ruedas',
    'silla de ruedas': 'Silla de Ruedas',
    'walker': 'Andador',
    'andador': 'Andador',
    'crutch': 'Muleta',
    'muleta': 'Muleta',
    'cane': 'Bastón',
    'baston': 'Bastón',
    'stretcher': 'Camilla',
    'camilla': 'Camilla',
    'gurney': 'Camilla',
    'hospital bed': 'Cama Hospitalaria',
    'cama hospitalaria': 'Cama Hospitalaria',
    'iv stand': 'Soporte de Suero',
    'soporte suero': 'Soporte de Suero',
    'oxygen tank': 'Tanque de Oxígeno',
    'tanque de oxigeno': 'Tanque de Oxígeno',
    'nebulizer': 'Nebulizador',
    'nebulizador': 'Nebulizador',
    'blood pressure monitor': 'Monitor de Presión Arterial',
    'tensiómetro': 'Monitor de Presión Arterial',
    'glucometer': 'Glucómetro',
    'glucometro': 'Glucómetro',
    'thermometer': 'Termómetro',
    'termometro': 'Termómetro',
    'pulse oximeter': 'Oxímetro de Pulso',
    'oximetro': 'Oxímetro de Pulso',
    'scale': 'Balanza',
    'balanza': 'Balanza',
    'first aid': 'Primeros Auxilios',
    'primeros auxilios': 'Primeros Auxilios',
    'bandage': 'Vendaje',
    'vendaje': 'Vendaje',
    'gauze': 'Gasa',
    'gasa': 'Gasa',
    'cotton': 'Algodón',
    'algodon': 'Algodón',
    'cotton swab': 'Hisopo',
    'hisopo': 'Hisopo',
    'cotton ball': 'Bola de Algodón',
    'antiseptic': 'Antiséptico',
    'antiseptico': 'Antiséptico',
    'disinfectant': 'Desinfectante',
    'desinfectante': 'Desinfectante',
    'band-aid': 'Curita',
    'curita': 'Curita',
    'adhesive bandage': 'Curita',
    'medical tape': 'Cinta Médica',
    'cinta medica': 'Cinta Médica',
    'splint': 'Férula',
    'ferula': 'Férula',
    'sling': 'Cabestrillo',
    'cabestrillo': 'Cabestrillo',
    'brace': 'Ortesis',
    'ortesis': 'Ortesis',
    'support': 'Soporte',
    'soporte': 'Soporte',
    'compression': 'Compresión',
    'compresion': 'Compresión',
    'ice pack': 'Bolsa de Hielo',
    'bolsa de hielo': 'Bolsa de Hielo',
    'heat pack': 'Bolsa de Calor',
    'bolsa de calor': 'Bolsa de Calor',
    'heating pad': 'Almohadilla Térmica',
    'almohadilla termica': 'Almohadilla Térmica',
    'cold compress': 'Compresa Fría',
    'compresa fria': 'Compresa Fría',
    'hot compress': 'Compresa Caliente',
    'compresa caliente': 'Compresa Caliente',
    'massage': 'Masaje',
    'masaje': 'Masaje',
    'massager': 'Masajeador',
    'masajeador': 'Masajeador',
    'vibrator': 'Vibrador',
    'vibrador': 'Vibrador',
    'thumper': 'Masajeador',
    'shiatsu': 'Shiatsu',
    'shiatsu': 'Shiatsu',
    'acupressure': 'Acupresura',
    'acupresura': 'Acupresura',
    'reflexology': 'Reflexología',
    'reflexologia': 'Reflexología',
    'acupuncture': 'Acupuntura',
    'acupuntura': 'Acupuntura',
    'chiropractic': 'Quiropráctica',
    'quiropractica': 'Quiropráctica',
    'physical therapy': 'Fisioterapia',
    'fisioterapia': 'Fisioterapia',
    'rehabilitation': 'Rehabilitación',
    'rehabilitacion': 'Rehabilitación',
    'orthopedic': 'Ortopédico',
    'ortopedico': 'Ortopédico',
    'podiatry': 'Podología',
    'podologia': 'Podología',
    'chiropody': 'Podología',
    'foot care': 'Cuidado de Pies',
    'cuidado de pies': 'Cuidado de Pies',
    'insole': 'Plantilla',
    'plantilla': 'Plantilla',
    'orthotic': 'Ortesis',
    'ortesis': 'Ortesis',
    'shoe insert': 'Plantilla',
    'heel pad': 'Almohadilla de Talón',
    'arch support': 'Soporte de Arco',
    'soporte arco': 'Soporte de Arco',
    'bunion corrector': 'Corrector de Juanetes',
    'corrector juanetes': 'Corrector de Juanetes',
    'toe separator': 'Separador de Dedos',
    'separador dedos': 'Separador de Dedos',
    'nail care': 'Cuidado de Uñas',
    'cuidado de uñas': 'Cuidado de Uñas',
    'manicure': 'Manicura',
    'manicura': 'Manicura',
    'pedicure': 'Pedicura',
    'pedicura': 'Pedicura',
    'nail art': 'Arte de Uñas',
    'arte de uñas': 'Arte de Uñas',
    'nail sticker': 'Calcomanía de Uñas',
    'calcomania de uñas': 'Calcomanía de Uñas',
    'nail polish': 'Esmalte',
    'esmalte': 'Esmalte',
    'top coat': 'Capa Superior',
    'capa superior': 'Capa Superior',
    'base coat': 'Capa Base',
    'capa base': 'Capa Base',
    'top coat': 'Top Coat',
    'base coat': 'Base Coat',
    'nail hardener': 'Endurecedor de Uñas',
    'endurecedor de uñas': 'Endurededor de Uñas',
    'nail strengthener': 'Fortalecedor de Uñas',
    'fortalecedor de uñas': 'Fortalecedor de Uñas',
    'cuticle oil': 'Aceite de Cutícula',
    'aceite de cuticula': 'Aceite de Cutícula',
    'hand cream': 'Crema de Manos',
    'crema de manos': 'Crema de Manos',
    'hand lotion': 'Loción de Manos',
    'locion de manos': 'Loción de Manos',
    'hand sanitizer': 'Sanitizante de Manos',
    'sanitizante de manos': 'Sanitizante de Manos',
    'hand wash': 'Lavado de Manos',
    'lavado de manos': 'Lavado de Manos',
    'hand soap': 'Jabón de Manos',
    'jabon de manos': 'Jabón de Manos',
    'hand towel': 'Toalla de Manos',
    'toalla de manos': 'Toalla de Manos',
    'paper towel': 'Toalla de Papel',
    'toalla de papel': 'Toalla de Papel',
    'tissue': 'Pañuelo',
    'panuelo': 'Pañuelo',
    'facial tissue': 'Pañuelo Facial',
    'servilleta': 'Servilleta',
    'napkin': 'Servilleta',
    'toilet paper': 'Papel Higiénico',
    'papel higienico': 'Papel Higiénico',
    'towel': 'Toalla',
    'toalla': 'Toalla',
    'bath towel': 'Toalla de Baño',
    'toalla de baño': 'Toalla de Baño',
    'beach towel': 'Toalla de Playa',
    'toalla de playa': 'Toalla de Playa',
    'kitchen towel': 'Toalla de Cocina',
    'toalla de cocina': 'Toalla de Cocina',
    'dish towel': 'Paño de Cocina',
    'pano de cocina': 'Paño de Cocina',
    'tea towel': 'Toalla de Té',
    'toalla de te': 'Toalla de Té',
    'handkerchief': 'Pañuelo',
    'panuelo': 'Pañuelo',
    'face mask': 'Mascarilla',
    'mascarilla': 'Mascarilla',
    'surgical mask': 'Mascarilla Quirúrgica',
    'mascarilla quirurgica': 'Mascarilla Quirúrgica',
    'n95': 'Mascarilla N95',
    'respirator': 'Respirador',
    'respirador': 'Respirador',
    'gloves': 'Guantes',
    'guantes': 'Guantes',
    'surgical gloves': 'Guantes Quirúrgicos',
    'guantes quirurgicos': 'Guantes Quirúrgicos',
    'disposable gloves': 'Guantes Desechables',
    'guantes desechables': 'Guantes Desechables',
    'rubber gloves': 'Guantes de Goma',
    'guantes de goma': 'Guantes de Goma',
    'latex gloves': 'Guantes de Látex',
    'guantes de látex': 'Guantes de Látex',
    'nitrile gloves': 'Guantes de Nitrilo',
    'guantes de nitrilo': 'Guantes de Nitrilo',
    'vinyl gloves': 'Guantes de Vinil',
    'guantes de vinil': 'Guantes de Vinil',
    'apron': 'Delantal',
    'delantal': 'Delantal',
    'lab coat': 'Bata',
    'bata': 'Bata',
    'scrubs': 'Uniforme Médico',
    'uniforme medico': 'Uniforme Médico',
    'gown': 'Bata',
    'gown': 'Bata',
    'surgical gown': 'Bata Quirúrgica',
    'bata quirurgica': 'Bata Quirúrgica',
    'isolation gown': 'Bata de Aislamiento',
    'bata de aislamiento': 'Bata de Aislamiento',
    'coverall': 'Overol',
    'overol': 'Overol',
    'jumpsuit': 'Enterizo',
    'enterizo': 'Enterizo',
    'boiler suit': 'Overol',
    'uniform': 'Uniforme',
    'uniforme': 'Uniforme',
    'workwear': 'Ropa de Trabajo',
    'ropa de trabajo': 'Ropa de Trabajo',
    'safety vest': 'Chaleco de Seguridad',
    'chaleco de seguridad': 'Chaleco de Seguridad',
    'high visibility': 'Alta Visibilidad',
    'alta visibilidad': 'Alta Visibilidad',
    'reflective': 'Reflectante',
    'reflectante': 'Reflectante',
    'hi-vis': 'Alta Visibilidad',
    'helmet': 'Casco',
    'casco': 'Casco',
    'hard hat': 'Casco de Seguridad',
    'casco de seguridad': 'Casco de Seguridad',
    'safety glasses': 'Gafas de Seguridad',
    'gafas de seguridad': 'Gafas de Seguridad',
    'safety goggles': 'Gafas de Seguridad',
    'gafas de seguridad': 'Gafas de Seguridad',
    'ear protection': 'Protección Auditiva',
    'proteccion auditiva': 'Protección Auditiva',
    'ear muffs': 'Orejeras',
    'orejeras': 'Orejeras',
    'ear plugs': 'Tapones Auditivos',
    'tapones auditivos': 'Tapones Auditivos',
    'face shield': 'Visor Facial',
    'visor facial': 'Visor Facial',
    'mask': 'Mascarilla',
    'mascarilla': 'Mascarilla',
    'respirator': 'Respirador',
    'respirador': 'Respirador',
    'dust mask': 'Mascarilla contra Polvo',
    'mascarilla polvo': 'Mascarilla contra Polvo',
    'gas mask': 'Mascarilla de Gas',
    'mascarilla de gas': 'Mascarilla de Gas',
    'chemical suit': 'Traje Químico',
    'traje quimico': 'Traje Químico',
    'hazmat suit': 'Traje HAZMAT',
    'traje hazmat': 'Traje HAZMAT',
    'anti radiation': 'Antirradiación',
    'antirradiacion': 'Antirradiación',
    'lead apron': 'Delantal de Plomo',
    'delantal de plomo': 'Delantal de Plomo',
    'radiation badge': 'Dosímetro',
    'dosimetro': 'Dosímetro',
    'geiger counter': 'Contador Geiger',
    'contador geiger': 'Contador Geiger',
    'radiation detector': 'Detector de Radiación',
    'detector de radiacion': 'Detector de Radiación',
    'smoke detector': 'Detector de Humo',
    'detector de humo': 'Detector de Humo',
    'fire extinguisher': 'Extintor',
    'extintor': 'Extintor',
    'fire blanket': 'Manta Ignífuga',
    'manta ignifuga': 'Manta Ignífuga',
    'first aid kit': 'Botiquín',
    'botiquin': 'Botiquín',
    'emergency kit': 'Kit de Emergencia',
    'kit de emergencia': 'Kit de Emergencia',
    'survival kit': 'Kit de Supervivencia',
    'kit de supervivencia': 'Kit de Supervivencia',
    'disaster kit': 'Kit de Desastre',
    'kit de desastre': 'Kit de Desastre',
    'earthquake kit': 'Kit de Terremoto',
    'kit de terremoto': 'Kit de Terremoto',
    'flood kit': 'Kit de Inundación',
    'kit de inundacion': 'Kit de Inundación',
    'hurricane kit': 'Kit de Huracán',
    'kit de huracan': 'Kit de Huracán',
    'tornado kit': 'Kit de Tornado',
    'kit de tornado': 'Kit de Tornado',
    'wildfire kit': 'Kit de Incendio',
    'kit de incendio': 'Kit de Incendio',
    'camping kit': 'Kit de Camping',
    'kit de camping': 'Kit de Camping',
    'hiking kit': 'Kit de Senderismo',
    'kit de senderismo': 'Kit de Senderismo',
    'backpacking kit': 'Kit de Mochilero',
    'kit de mochilero': 'Kit de Mochilero',
    'travel kit': 'Kit de Viaje',
    'kit de viaje': 'Kit de Viaje',
    'toiletry kit': 'Kit de Aseo',
    'kit de aseo': 'Kit de Aseo',
    'hygiene kit': 'Kit de Higiene',
    'kit de higiene': 'Kit de Higiene',
    'grooming kit': 'Kit de Afeitado',
    'kit de afeitado': 'Kit de Afeitado',
    'shaving kit': 'Kit de Afeitado',
    'kit de afeitado': 'Kit de Afeitado',
    'makeup kit': 'Kit de Maquillaje',
    'kit de maquillaje': 'Kit de Maquillaje',
    'cosmetics kit': 'Kit de Cosméticos',
    'kit de cosmeticos': 'Kit de Cosméticos',
    'nail kit': 'Kit de Uñas',
    'kit de uñas': 'Kit de Uñas',
    'manicure kit': 'Kit de Manicura',
    'kit de manicura': 'Kit de Manicura',
    'pedicure kit': 'Kit de Pedicura',
    'kit de pedicura': 'Kit de Pedicura',
    'sewing kit': 'Kit de Costura',
    'kit de costura': 'Kit de Costura',
    'craft kit': 'Kit de Artesanía',
    'kit de artesania': 'Kit de Artesanía',
    'art kit': 'Kit de Arte',
    'kit de arte': 'Kit de Arte',
    'painting kit': 'Kit de Pintura',
    'kit de pintura': 'Kit de Pintura',
    'drawing kit': 'Kit de Dibujo',
    'kit de dibujo': 'Kit de Dibujo',
    'sketching kit': 'Kit de Bocetos',
    'kit de bocetos': 'Kit de Bocetos',
    'calligraphy kit': 'Kit de Caligrafía',
    'kit de caligrafia': 'Kit de Caligrafía',
    'writing kit': 'Kit de Escritura',
    'kit de escritura': 'Kit de Escritura',
    'notebook kit': 'Kit de Cuadernos',
    'kit de cuadernos': 'Kit de Cuadernos',
    'stationery kit': 'Kit de Papelería',
    'kit de papeleria': 'Kit de Papelería',
    'office kit': 'Kit de Oficina',
    'kit de oficina': 'Kit de Oficina',
    'school kit': 'Kit Escolar',
    'kit escolar': 'Kit Escolar',
    'student kit': 'Kit de Estudiante',
    'kit de estudiante': 'Kit de Estudiante',
    'teacher kit': 'Kit de Maestro',
    'kit de maestro': 'Kit de Maestro',
    'professor kit': 'Kit de Profesor',
    'kit de profesor': 'Kit de Profesor',
    'classroom kit': 'Kit de Aula',
    'kit de aula': 'Kit de Aula',
    'lab kit': 'Kit de Laboratorio',
    'kit de laboratorio': 'Kit de Laboratorio',
    'science kit': 'Kit de Ciencias',
    'kit de ciencias': 'Kit de Ciencias',
    'chemistry kit': 'Kit de Química',
    'kit de quimica': 'Kit de Química',
    'physics kit': 'Kit de Física',
    'kit de fisica': 'Kit de Física',
    'biology kit': 'Kit de Biología',
    'kit de biologia': 'Kit de Biología',
    'math kit': 'Kit de Matemáticas',
    'kit de matematicas': 'Kit de Matemáticas',
    'geometry kit': 'Kit de Geometría',
    'kit de geometria': 'Kit de Geometría',
    'algebra kit': 'Kit de Álgebra',
    'kit de algebra': 'Kit de Álgebra',
    'trigonometry kit': 'Kit de Trigonometría',
    'kit de trigonometria': 'Kit de Trigonometría',
    'calculus kit': 'Kit de Cálculo',
    'kit de calculo': 'Kit de Cálculo',
    'statistics kit': 'Kit de Estadística',
    'kit de estadistica': 'Kit de Estadística',
    'probability kit': 'Kit de Probabilidad',
    'kit de probabilidad': 'Kit de Probabilidad',
    'logic kit': 'Kit de Lógica',
    'kit de logica': 'Kit de Lógica',
    'philosophy kit': 'Kit de Filosofía',
    'kit de filosofia': 'Kit de Filosofía',
    'psychology kit': 'Kit de Psicología',
    'kit de psicologia': 'Kit de Psicología',
    'sociology kit': 'Kit de Sociología',
    'kit de sociologia': 'Kit de Sociología',
    'anthropology kit': 'Kit de Antropología',
    'kit de antropologia': 'Kit de Antropología',
    'history kit': 'Kit de Historia',
    'kit de historia': 'Kit de Historia',
    'geography kit': 'Kit de Geografía',
    'kit de geografia': 'Kit de Geografía',
    'literature kit': 'Kit de Literatura',
    'kit de literatura': 'Kit de Literatura',
    'language kit': 'Kit de Idiomas',
    'kit de idiomas': 'Kit de Idiomas',
    'english kit': 'Kit de Inglés',
    'kit de ingles': 'Kit de Inglés',
    'spanish kit': 'Kit de Español',
    'kit de espanol': 'Kit de Español',
    'french kit': 'Kit de Francés',
    'kit de frances': 'Kit de Francés',
    'german kit': 'Kit de Alemán',
    'kit de aleman': 'Kit de Alemán',
    'italian kit': 'Kit de Italiano',
    'kit de italiano': 'Kit de Italiano',
    'portuguese kit': 'Kit de Portugués',
    'kit de portugues': 'Kit de Portugués',
    'chinese kit': 'Kit de Chino',
    'kit de chino': 'Kit de Chino',
    'japanese kit': 'Kit de Japonés',
    'kit de japones': 'Kit de Japonés',
    'korean kit': 'Kit de Coreano',
    'kit de coreano': 'Kit de Coreano',
    'arabic kit': 'Kit de Árabe',
    'kit de arabe': 'Kit de Árabe',
    'russian kit': 'Kit de Ruso',
    'kit de ruso': 'Kit de Ruso',
    'hindi kit': 'Kit de Hindi',
    'kit de hindi': 'Kit de Hindi',
    'swahili kit': 'Kit de Suajili',
    'kit de suajili': 'Kit de Suajili',
    'navajo kit': 'Kit de Navajo',
    'kit de navajo': 'Kit de Navajo',
    'esperanto kit': 'Kit de Esperanto',
    'kit de esperanto': 'Kit de Esperanto',
    'latin kit': 'Kit de Latín',
    'kit de latin': 'Kit de Latín',
    'greek kit': 'Kit de Griego',
    'kit de griego': 'Kit de Griego',
    'hebrew kit': 'Kit de Hebreo',
    'kit de hebreo': 'Kit de Hebreo',
    'sanskrit kit': 'Kit de Sánscrito',
    'kit de sanscrito': 'Kit de Sánscrito',
    'ayurveda kit': 'Kit de Ayurveda',
    'kit de ayurveda': 'Kit de Ayurveda',
    'yoga kit': 'Kit de Yoga',
    'kit de yoga': 'Kit de Yoga',
    'meditation kit': 'Kit de Meditación',
    'kit de meditacion': 'Kit de Meditación',
    'mindfulness kit': 'Kit de Mindfulness',
    'kit de mindfulness': 'Kit de Mindfulness',
    'zen kit': 'Kit de Zen',
    'kit de zen': 'Kit de Zen',
    'buddhism kit': 'Kit de Budismo',
    'kit de budismo': 'Kit de Budismo',
    'taoism kit': 'Kit de Taoísmo',
    'kit de taoismo': 'Kit de Taoísmo',
    'confucianism kit': 'Kit de Confucianismo',
    'kit de confucianismo': 'Kit de Confucianismo',
    'shinto kit': 'Kit de Sintoísmo',
    'kit de sintoismo': 'Kit de Sintoísmo',
    'jainism kit': 'Kit de Jainismo',
    'kit de jainismo': 'Kit de Jainismo',
    'sikhism kit': 'Kit de Sijismo',
    'kit de sijismo': 'Kit de Sijismo',
    'hinduism kit': 'Kit de Hinduísmo',
    'kit de hinduismo': 'Kit de Hinduísmo',
    'christianity kit': 'Kit de Cristianismo',
    'kit de cristianismo': 'Kit de Cristianismo',
    'islam kit': 'Kit de Islam',
    'kit de islam': 'Kit de Islam',
    'judaism kit': 'Kit de Judaísmo',
    'kit de judaismo': 'Kit de Judaísmo',
    'atheism kit': 'Kit de Ateísmo',
    'kit de ateismo': 'Kit de Ateísmo',
    'agnosticism kit': 'Kit de Agnosticismo',
    'kit de agnosticismo': 'Kit de Agnosticismo',
    'humanism kit': 'Kit de Humanismo',
    'kit de humanismo': 'Kit de Humanismo',
    'existentialism kit': 'Kit de Existencialismo',
    'kit de existencialismo': 'Kit de Existencialismo',
    'nihilism kit': 'Kit de Nihilismo',
    'kit de nihilismo': 'Kit de Nihilismo',
    'absurdism kit': 'Kit de Absurdismo',
    'kit de absurdismo': 'Kit de Absurdismo',
    'stoicism kit': 'Kit de Estoicismo',
    'kit de estoicismo': 'Kit de Estoicismo',
    'epicureanism kit': 'Kit de Epicureísmo',
    'kit de epicureismo': 'Kit de Epicureísmo',
    'pragmatism kit': 'Kit de Pragmatismo',
    'kit de pragmatismo': 'Kit de Pragmatismo',
    'utilitarianism kit': 'Kit de Utilitarismo',
    'kit de utilitarismo': 'Kit de Utilitarismo',
    'capitalism kit': 'Kit de Capitalismo',
    'kit de capitalismo': 'Kit de Capitalismo',
    'socialism kit': 'Kit de Socialismo',
    'kit de socialismo': 'Kit de Socialismo',
    'communism kit': 'Kit de Comunismo',
    'kit de comunismo': 'Kit de Comunismo',
    'anarchism kit': 'Kit de Anarquismo',
    'kit de anarchismo': 'Kit de Anarquismo',
    'fascism kit': 'Kit de Fascismo',
    'kit de fascismo': 'Kit de Fascismo',
    'nazism kit': 'Kit de Nazismo',
    'kit de nazismo': 'Kit de Nazismo',
    'democracy kit': 'Kit de Democracia',
    'kit de democracia': 'Kit de Democracia',
    'republic kit': 'Kit de República',
    'kit de república': 'Kit de República',
    'monarchy kit': 'Kit de Monarquía',
    'kit de monarquia': 'Kit de Monarquía',
    'dictatorship kit': 'Kit de Dictadura',
    'kit de dictadura': 'Kit de Dictadura',
    'tyranny kit': 'Kit de Tiranía',
    'kit de tirania': 'Kit de Tiranía',
    'oligarchy kit': 'Kit de Oligarquía',
    'kit de oligarquia': 'Kit de Oligarquía',
    'plutocracy kit': 'Kit de Plutocracia',
    'kit de plutocracia': 'Kit de Plutocracia',
    'theocracy kit': 'Kit de Teocracia',
    'kit de teocracia': 'Kit de Teocracia',
    'meritocracy kit': 'Kit de Meritocracia',
    'kit de meritocracia': 'Kit de Meritocracia',
    'technocracy kit': 'Kit de Tecnocracia',
    'kit de tecnocracia': 'Kit de Tecnocracia',
    'bureaucracy kit': 'Kit de Burocracia',
    'kit de burocracia': 'Kit de Burocracia',
    'kakistocracy kit': 'Kit de Kakistocracia',
    'kit de kakistocracia': 'Kit de Kakistocracia',
    'kleptocracy kit': 'Kit de Cleptocracia',
    'kit de cleptocracia': 'Kit de Cleptocracia',
    'corporatocracy kit': 'Kit de Corporatocracia',
    'kit de corporatocracia': 'Kit de Corporatocracia',
    'mobocracy kit': 'Kit de Mobocracia',
    'kit de mobocracia': 'Kit de Mobocracia',
    'gerontocracy kit': 'Kit de Gerontocracia',
    'kit de gerontocracia': 'Kit de Gerontocracia',
    'theocracy kit': 'Kit de Teocracia',
    'kit de teocracia': 'Kit de Teocracia',
    'matriarchy kit': 'Kit de Matriarcado',
    'kit de matriarcado': 'Kit de Matriarcado',
    'patriarchy kit': 'Kit de Patriarcado',
    'kit de patriarcado': 'Kit de Patriarcado',
    'egalitarianism kit': 'Kit de Egalitarismo',
    'kit de egalitarismo': 'Kit de Egalitarismo',
    'feminism kit': 'Kit de Feminismo',
    'kit de feminismo': 'Kit de Feminismo',
    'masculism kit': 'Kit de Masculismo',
    'kit de masculismo': 'Kit de Masculismo',
    'gender equality kit': 'Kit de Igualdad de Género',
    'kit de igualdad de genero': 'Kit de Igualdad de Género',
    'lgbtq kit': 'Kit de LGBTQ',
    'kit de lgbtq': 'Kit de LGBTQ',
    'gay rights kit': 'Kit de Derechos Gay',
    'kit de derechos gay': 'Kit de Derechos Gay',
    'lesbian rights kit': 'Kit de Derechos Lesbianas',
    'kit de derechos lesbianas': 'Kit de Derechos Lesbianas',
    'bisexual rights kit': 'Kit de Derechos Bisexuales',
    'kit de derechos bisexuales': 'Kit de Derechos Bisexuales',
    'transgender rights kit': 'Kit de Derechos Transgénero',
    'kit de derechos transgenero': 'Kit de Derechos Transgénero',
    'queer rights kit': 'Kit de Derechos Queer',
    'kit de derechos queer': 'Kit de Derechos Queer',
    'intersex rights kit': 'Kit de Derechos Intersex',
    'kit de derechos intersex': 'Kit de Derechos Intersex',
    'asexual rights kit': 'Kit de Derechos Asexuales',
    'kit de derechos asexuales': 'Kit de Derechos Asexuales',
    'pansexual rights kit': 'Kit de Derechos Pansexuales',
    'kit de derechos pansexuales': 'Kit de Derechos Pansexuales',
    'non-binary rights kit': 'Kit de Derechos No Binarios',
    'kit de derechos no binarios': 'Kit de Derechos No Binarios',
    'genderfluid rights kit': 'Kit de Derechos Genderfluid',
    'kit de derechos genderfluid': 'Kit de Derechos Genderfluid',
    'agender rights kit': 'Kit de Derechos Agénero',
    'kit de derechos agenero': 'Kit de Derechos Agénero',
    'bigender rights kit': 'Kit de Derechos Bigénero',
    'kit de derechos bigenero': 'Kit de Derechos Bigénero',
    'pangender rights kit': 'Kit de Derechos Pangénero',
    'kit de derechos pangenero': 'Kit de Derechos Pangénero',
    'demiboy rights kit': 'Kit de Derechos Demichico',
    'kit de derechos demichico': 'Kit de Derechos Demichico',
    'demigirl rights kit': 'Kit de Derechos Demichica',
    'kit de derechos demichica': 'Kit de Derechos Demichica',
    'demigender rights kit': 'Kit de Derechos Demigénero',
    'kit de derechos demigenero': 'Kit de Derechos Demigénero',
    'neutrois rights kit': 'Kit de Derechos Neutrois',
    'kit de derechos neutrois': 'Kit de Derechos Neutrois',
    'trigender rights kit': 'Kit de Derechos Trigénero',
    'kit de derechos trigenero': 'Kit de Derechos Trigénero',
    'polygender rights kit': 'Kit de Derechos Poligénero',
    'kit de derechos poligenero': 'Kit de Derechos Poligénero',
    'greygender rights kit': 'Kit de Derechos Greygénero',
    'kit de derechos greygenero': 'Kit de Derechos Greygénero',
    'aporagender rights kit': 'Kit de Derechos Aporagénero',
    'kit de derechos aporagenero': 'Kit de Derechos Aporagénero',
    'maverique rights kit': 'Kit de Derechos Maverique',
    'kit de derechos maverique': 'Kit de Derechos Maverique',
    'xenogender rights kit': 'Kit de Derechos Xenogénero',
    'kit de derechos xenogenero': 'Kit de Derechos Xenogénero',
    'autigender rights kit': 'Kit de Derechos Autigénero',
    'kit de derechos autigenero': 'Kit de Derechos Autigénero',
    'faegender rights kit': 'Kit de Derechos Faegénero',
    'kit de derechos faegenero': 'Kit de Derechos Faegénero',
    'flowegender rights kit': 'Kit de Derechos Flowegénero',
    'kit de derechos flowegenero': 'Kit de Derechos Flowegénero',
    'flowergender rights kit': 'Kit de Derechos Flowergénero',
    'kit de derechos flowergenero': 'Kit de Derechos Flowergénero',
    'stargender rights kit': 'Kit de Derechos Stargénero',
    'kit de derechos stargenero': 'Kit de Derechos Stargénero',
    'sungender rights kit': 'Kit de Derechos Sungénero',
    'kit de derechos sungenero': 'Kit de Derechos Sungénero',
    'moongender rights kit': 'Kit de Derechos Moongénero',
    'kit de derechos moongenero': 'Kit de Derechos Moongénero',
    'celestialgender rights kit': 'Kit de Derechos Celestialgénero',
    'kit de derechos celestialgenero': 'Kit de Derechos Celestialgénero',
    'astralgender rights kit': 'Kit de Derechos Astralgénero',
    'kit de derechos astralgenero': 'Kit de Derechos Astralgénero',
    'cosmicgender rights kit': 'Kit de Derechos Cosmicgénero',
    'kit de derechos cosmicgenero': 'Kit de Derechos Cosmicgénero',
    'galaxygender rights kit': 'Kit de Derechos Galaxygénero',
    'kit de derechos galaxygenero': 'Kit de Derechos Galaxygénero',
    'universegender rights kit': 'Kit de Derechos Universegénero',
    'kit de derechos universegenero': 'Kit de Derechos Universegénero',
    'multiversegender rights kit': 'Kit de Derechos Multiversegénero',
    'kit de derechos multiversegenero': 'Kit de Derechos Multiversegénero',
    'omniversegender rights kit': 'Kit de Derechos Omniversegénero',
    'kit de derechos omniversegenero': 'Kit de Derechos Omniversegénero',
    'dimensiongender rights kit': 'Kit de Derechos Dimensiongénero',
    'kit de derechos dimensiongenero': 'Kit de Derechos Dimensiongénero',
    'planetarygender rights kit': 'Kit de Derechos Planetarygénero',
    'kit de derechos planetarygenero': 'Kit de Derechos Planetarygénero',
    'terrestrialgender rights kit': 'Kit de Derechos Terrestrialgénero',
    'kit de derechos terrestrialgenero': 'Kit de Derechos Terrestrialgénero',
    'lunargender rights kit': 'Kit de Derechos Lunar género',
    'kit de derechos lunargender': 'Kit de Derechos Lunar género',
    'solargender rights kit': 'Kit de Derechos Solar género',
    'kit de derechos solargender': 'Kit de Derechos Solar género',
    'stelargender rights kit': 'Kit de Derechos Stellar género',
    'kit de derechos stelargender': 'Kit de Derechos Stellar género',
    'nebulagender rights kit': 'Kit de Derechos Nebula género',
    'kit de derechos nebulagender': 'Kit de Derechos Nebula género',
    'blackholegender rights kit': 'Kit de Derechos Black Hole género',
    'kit de derechos blackholegender': 'Kit de Derechos Black Hole género',
    'pulsargender rights kit': 'Kit de Derechos Pulsar género',
    'kit de derechos pulsargender': 'Kit de Derechos Pulsar género',
    'quasargender rights kit': 'Kit de Derechos Quasar género',
    'kit de derechos quasargender': 'Kit de Derechos Quasar género',
    'supernovagender rights kit': 'Kit de Derechos Supernova género',
    'kit de derechos supernovagender': 'Kit de Derechos Supernova género',
    'magnetar gender rights kit': 'Kit de Derechos Magnetar género',
    'kit de derechos magnetar gender': 'Kit de Derechos Magnetar género',
    'white dwarf gender rights kit': 'Kit de Derechos White Dwarf género',
    'kit de derechos white dwarf gender': 'Kit de Derechos White Dwarf género',
    'brown dwarf gender rights kit': 'Kit de Derechos Brown Dwarf género',
    'kit de derechos brown dwarf gender': 'Kit de Derechos Brown Dwarf género',
    'red dwarf gender rights kit': 'Kit de Derechos Red Dwarf género',
    'kit de derechos red dwarf gender': 'Kit de Derechos Red Dwarf género',
    'yellow dwarf gender rights kit': 'Kit de Derechos Yellow Dwarf género',
    'kit de derechos yellow dwarf gender': 'Kit de Derechos Yellow Dwarf género',
    'orange dwarf gender rights kit': 'Kit de Derechos Orange Dwarf género',
    'kit de derechos orange dwarf gender': 'Kit de Derechos Orange Dwarf género',
    'blue giant gender rights kit': 'Kit de Derechos Blue Giant género',
    'kit de derechos blue giant gender': 'Kit de Derechos Blue Giant género',
    'red giant gender rights kit': 'Kit de Derechos Red Giant género',
    'kit de derechos red giant gender': 'Kit de Derechos Red Giant género',
    'yellow giant gender rights kit': 'Kit de Derechos Yellow Giant género',
    'kit de derechos yellow giant gender': 'Kit de Derechos Yellow Giant género',
    'orange giant gender rights kit': 'Kit de Derechos Orange Giant género',
    'kit de derechos orange giant gender': 'Kit de Derechos Orange Giant género',
    'blue supergiant gender rights kit': 'Kit de Derechos Blue Supergiant género',
    'kit de derechos blue supergiant gender': 'Kit de Derechos Blue Supergiant género',
    'red supergiant gender rights kit': 'Kit de Derechos Red Supergiant género',
    'kit de derechos red supergiant gender': 'Kit de Derechos Red Supergiant género',
    'yellow supergiant gender rights kit': 'Kit de Derechos Yellow Supergiant género',
    'kit de derechos yellow supergiant gender': 'Kit de Derechos Yellow Supergiant género',
    'orange supergiant gender rights kit': 'Kit de Derechos Orange Supergiant género',
    'kit de derechos orange supergiant gender': 'Kit de Derechos Orange Supergiant género',
    'blue hypergiant gender rights kit': 'Kit de Derechos Blue Hypergiant género',
    'kit de derechos blue hypergiant gender': 'Kit de Derechos Blue Hypergiant género',
    'red hypergiant gender rights kit': 'Kit de Derechos Red Hypergiant género',
    'kit de derechos red hypergiant gender': 'Kit de Derechos Red Hypergiant género',
    'yellow hypergiant gender rights kit': 'Kit de Derechos Yellow Hypergiant género',
    'kit de derechos yellow hypergiant gender': 'Kit de Derechos Yellow Hypergiant género',
    'orange hypergiant gender rights kit': 'Kit de Derechos Orange Hypergiant género',
    'kit de derechos orange hypergiant gender': 'Kit de Derechos Orange Hypergiant género',
    'white hypergiant gender rights kit': 'Kit de Derechos White Hypergiant género',
    'kit de derechos white hypergiant gender': 'Kit de Derechos White Hypergiant género',
    'luminous blue variable gender rights kit': 'Kit de Derechos Luminous Blue Variable género',
    'kit de derechos luminous blue variable gender': 'Kit de Derechos Luminous Blue Variable género',
    'wolf-rayet star gender rights kit': 'Kit de Derechos Wolf-Rayet Star género',
    'kit de derechos wolf-rayet star gender': 'Kit de Derechos Wolf-Rayet Star género',
    'be star gender rights kit': 'Kit de Derechos Be Star género',
    'kit de derechos be star gender': 'Kit de Derechos Be Star género',
    'ae galactica star gender rights kit': 'Kit de Derechos AE Galactica Star género',
    'kit de derechos ae galactica star gender': 'Kit de Derechos AE Galactica Star género',
    'rr lyrae variable gender rights kit': 'Kit de Derechos RR Lyrae Variable género',
    'kit de derechos rr lyrae variable gender': 'Kit de Derechos RR Lyrae Variable género',
    'cepheid variable gender rights kit': 'Kit de Derechos Cepheid Variable género',
    'kit de derechos cepheid variable gender': 'Kit de Derechos Cepheid Variable género',
    'mira variable gender rights kit': 'Kit de Derechos Mira Variable género',
    'kit de derechos mira variable gender': 'Kit de Derechos Mira Variable género',
    'eclipsing binary gender rights kit': 'Kit de Derechos Eclipsing Binary género',
    'kit de derechos eclipsing binary gender': 'Kit de Derechos Eclipsing Binary género',
    'spectroscopic binary gender rights kit': 'Kit de Derechos Spectroscopic Binary género',
    'kit de derechos spectroscopic binary gender': 'Kit de Derechos Spectroscopic Binary género',
    'visual binary gender rights kit': 'Kit de Derechos Visual Binary género',
    'kit de derechos visual binary gender': 'Kit de Derechos Visual Binary género',
    'astrometric binary gender rights kit': 'Kit de Derechos Astrometric Binary género',
    'kit de derechos astrometric binary gender': 'Kit de Derechos Astrometric Binary género',
    'x-ray binary gender rights kit': 'Kit de Derechos X-ray Binary género',
    'kit de derechos x-ray binary gender': 'Kit de Derechos X-ray Binary género',
    'low-mass x-ray binary gender rights kit': 'Kit de Derechos Low-mass X-ray Binary género',
    'kit de derechos low-mass x-ray binary gender': 'Kit de Derechos Low-mass X-ray Binary género',
    'high-mass x-ray binary gender rights kit': 'Kit de Derechos High-mass X-ray Binary género',
    'kit de derechos high-mass x-ray binary gender': 'Kit de Derechos High-mass X-ray Binary género',
    'microquasar gender rights kit': 'Kit de Derechos Microquasar género',
    'kit de derechos microquasar gender': 'Kit de Derechos Microquasar género',
    'active galactic nucleus gender rights kit': 'Kit de Derechos Active Galactic Nucleus género',
    'kit de derechos active galactic nucleus gender': 'Kit de Derechos Active Galactic Nucleus género',
    'quasar gender rights kit': 'Kit de Derechos Quasar género',
    'kit de derechos quasar gender': 'Kit de Derechos Quasar género',
    'blazar gender rights kit': 'Kit de Derechos Blazar género',
    'kit de derechos blazar gender': 'Kit de Derechos Blazar género',
    'seyfert galaxy gender rights kit': 'Kit de Derechos Seyfert Galaxy género',
    'kit de derechos seyfert galaxy gender': 'Kit de Derechos Seyfert Galaxy género',
    'radio galaxy gender rights kit': 'Kit de Derechos Radio Galaxy género',
    'kit de derechos radio galaxy gender': 'Kit de Derechos Radio Galaxy género',
    'starburst galaxy gender rights kit': 'Kit de Derechos Starburst Galaxy género',
    'kit de derechos starburst galaxy gender': 'Kit de Derechos Starburst Galaxy género',
    'irregular galaxy gender rights kit': 'Kit de Derechos Irregular Galaxy género',
    'kit de derechos irregular galaxy gender': 'Kit de Derechos Irregular Galaxy género',
    'elliptical galaxy gender rights kit': 'Kit de Derechos Elliptical Galaxy género',
    'kit de derechos elliptical galaxy gender': 'Kit de Derechos Elliptical Galaxy género',
    'spiral galaxy gender rights kit': 'Kit de Derechos Spiral Galaxy género',
    'kit de derechos spiral galaxy gender': 'Kit de Derechos Spiral Galaxy género',
    'barred spiral galaxy gender rights kit': 'Kit de Derechos Barred Spiral Galaxy género',
    'kit de derechos barred spiral galaxy gender': 'Kit de Derechos Barred Spiral Galaxy género',
    'lenticular galaxy gender rights kit': 'Kit de Derechos Lenticular Galaxy género',
    'kit de derechos lenticular galaxy gender': 'Kit de Derechos Lenticular Galaxy género',
    'dwarf galaxy gender rights kit': 'Kit de Derechos Dwarf Galaxy género',
    'kit de derechos dwarf galaxy gender': 'Kit de Derechos Dwarf Galaxy género',
    'giant galaxy gender rights kit': 'Kit de Derechos Giant Galaxy género',
    'kit de derechos giant galaxy gender': 'Kit de Derechos Giant Galaxy género',
    'supergiant galaxy gender rights kit': 'Kit de Derechos Supergiant Galaxy género',
    'kit de derechos supergiant galaxy gender': 'Kit de Derechos Supergiant Galaxy género',
    'hypergiant galaxy gender rights kit': 'Kit de Derechos Hypergiant Galaxy género',
    'kit de derechos hypergiant galaxy gender': 'Kit de Derechos Hypergiant Galaxy género',
    'mega galaxy gender rights kit': 'Kit de Derechos Mega Galaxy género',
    'kit de derechos mega galaxy gender': 'Kit de Derechos Mega Galaxy género',
    'giga galaxy gender rights kit': 'Kit de Derechos Giga Galaxy género',
    'kit de derechos giga galaxy gender': 'Kit de Derechos Giga Galaxy género',
    'tera galaxy gender rights kit': 'Kit de Derechos Tera Galaxy género',
    'kit de derechos tera galaxy gender': 'Kit de Derechos Tera Galaxy género',
    'peta galaxy gender rights kit': 'Kit de Derechos Peta Galaxy género',
    'kit de derechos peta galaxy gender': 'Kit de Derechos Peta Galaxy género',
    'exa galaxy gender rights kit': 'Kit de Derechos Exa Galaxy género',
    'kit de derechos exa galaxy gender': 'Kit de Derechos Exa Galaxy género',
    'zetta galaxy gender rights kit': 'Kit de Derechos Zetta Galaxy género',
    'kit de derechos zetta galaxy gender': 'Kit de Derechos Zetta Galaxy género',
    'yotta galaxy gender rights kit': 'Kit de Derechos Yotta Galaxy género',
    'kit de derechos yotta galaxy gender': 'Kit de Derechos Yotta Galaxy género',
    'ronna galaxy gender rights kit': 'Kit de Derechos Ronna Galaxy género',
    'kit de derechos ronna galaxy gender': 'Kit de Derechos Ronna Galaxy género',
    'quetta galaxy gender rights kit': 'Kit de Derechos Quetta Galaxy género',
    'kit de derechos quetta galaxy gender': 'Kit de Derechos Quetta Galaxy género',
}

def clasificar_producto(nombre):
    """Clasifica un producto por marca y tipo basado en su nombre"""
    nombre_lower = nombre.lower()
    
    # Buscar marca
    marca = "Genérica"
    for keyword, marca_nombre in MARCAS_CONOCIDAS.items():
        if keyword in nombre_lower:
            marca = marca_nombre
            break
    
    # Buscar tipo
    tipo = "Otro"
    for keyword, tipo_nombre in TIPOS_POR_PALABRA_CLAVE.items():
        if keyword in nombre_lower:
            tipo = tipo_nombre
            break
    
    return marca, tipo

def scrapear_producto(nombre_producto, marca, tipo):
    """Busca información técnica e imágenes de un producto en internet"""
    print(f"\nBuscando: {nombre_producto}")
    
    # Primero buscamos en DuckDuckGo para obtener resultados
    query = f"{nombre_producto} especificaciones técnicas"
    url = f"https://html.duckduckgo.com/html/?q={query.replace(' ', '+')}"
    
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
    }
    
    try:
        response = requests.get(url, headers=headers, timeout=10)
        if response.status_code == 200:
            soup = BeautifulSoup(response.text, 'html.parser')
            
            # Buscar snippets con información técnica
            resultados = soup.find_all('a', class_='result__snippet')
            especificaciones = []
            
            for resultado in resultados[:3]:  # Top 3 resultados
                texto = resultado.get_text()
                if any(palabra in texto.lower() for palabra in ['w', 'v', 'a', 'gb', 'tb', 'mb', 'hz', 'ghz', 'mm', 'pulgadas', 'inch', 'resolución', 'capacidad']):
                    especificaciones.append(texto)
            
            # Buscar imágenes
            imagenes_url = f"https://html.duckduckgo.com/html/?q={nombre_producto.replace(' ', '+')}&iar=images"
            response_img = requests.get(imagenes_url, headers=headers, timeout=10)
            imagenes = []
            
            if response_img.status_code == 200:
                soup_img = BeautifulSoup(response_img.text, 'html.parser')
                resultados_img = soup_img.find_all('a', class_='result__image')
                for img in resultados_img[:3]:  # Top 3 imágenes
                    href = img.get('href', '')
                    if href.startswith('http'):
                        imagenes.append(href)
            
            return {
                'especificaciones': especificaciones,
                'imagenes': imagenes
            }
    except Exception as e:
        print(f"  Error: {e}")
    
    return {'especificaciones': [], 'imagenes': []}

def main():
    # Leer el archivo Excel
    print("Leyendo archivo LISTADO_CLEAN.xlsx...")
    df = pd.read_excel(r'C:\Users\Usuario\Desktop\desarollo\LBDC\LISTADO_CLEAN.xlsx')
    
    # Eliminar fila de encabezado duplicada (si existe)
    df = df[df['NOMBRE'] != 'NOMBRE']
    
    # Eliminar filas sin precio
    df = df[df['PRECIO'].notna()]
    
    print(f"Total de productos encontrados: {len(df)}")
    
    # Clasificar productos
    print("\nClasificando productos...")
    df['MARCA'] = df['NOMBRE'].apply(lambda x: clasificar_producto(str(x))[0])
    df['TIPO'] = df['NOMBRE'].apply(lambda x: clasificar_producto(str(x))[1])
    
    # Mostrar estadísticas
    print("\nDistribución por marcas (top 20):")
    print(df['MARCA'].value_counts().head(20))
    
    print("\nDistribución por tipo (top 20):")
    print(df['TIPO'].value_counts().head(20))
    
    # Guardar clasificación
    output_file = r'C:\Users\Usuario\Desktop\desarollo\LBDC\productos_clasificados.xlsx'
    df.to_excel(output_file, index=False)
    print(f"\nClasificación guardada en: {output_file}")
    
    # Hacer scraping para los primeros 10 productos (ejemplo)
    print("\n" + "="*50)
    print("EJEMPLO DE SCRAPING (primeros 10 productos)")
    print("="*50)
    
    productos_scrapeados = []
    for idx, row in df.head(10).iterrows():
        nombre = str(row['NOMBRE'])
        marca = row['MARCA']
        tipo = row['TIPO']
        
        datos = scrapear_producto(nombre, marca, tipo)
        
        productos_scrapeados.append({
            'nombre': nombre,
            'precio': row['PRECIO'],
            'marca': marca,
            'tipo': tipo,
            'especificaciones': '; '.join(datos['especificaciones']),
            'imagenes': '; '.join(datos['imagenes'])
        })
        
        # Pausa para no ser bloqueado
        time.sleep(random.uniform(1, 3))
    
    # Guardar resultados del scraping
    df_scrape = pd.DataFrame(productos_scrapeados)
    scrape_file = r'C:\Users\Usuario\Desktop\desarollo\LBDC\productos_scrapeados_ejemplo.xlsx'
    df_scrape.to_excel(scrape_file, index=False)
    print(f"\nEjemplo de scraping guardado en: {scrape_file}")
    
    # Resumen
    print("\n" + "="*50)
    print("RESUMEN")
    print("="*50)
    print(f"Total productos: {len(df)}")
    print(f"Únicas marcas: {df['MARCA'].nunique()}")
    print(f"Únicos tipos: {df['TIPO'].nunique()}")
    print(f"Scrapeados (ejemplo): {len(df_scrape)}")
    
    print("\nPara hacer scraping completo de todos los productos,")
    print("ejecuta el siguiente script (descomentado):")
    print("""
# Descomentar para scraping completo (TARDA MUCHO)
"""
    )

if __name__ == "__main__":
    main()
